# Hackathon Hospitality 
<hr/>

In [9]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Data - in 
<hr/>

In [10]:
# hotels & air bnb in NY 

df = pd.read_csv('../data/new_york_hotels.csv' )
print(df.shape)
df.head(3)

(1631, 11)

,ean_hotel_id,name,address1,city,state_province,postal_code,latitude,longitude,star_rating,high_rate,low_rate
0,269955,Hilton Garden Inn Albany/SUNY Area,1389 Washington Ave,Albany,NY,12206,42.68751,-73.81643,3.0,154.0272,124.0216
1,113431,Courtyard by Marriott Albany Thruway,1455 Washington Avenue,Albany,NY,12206,42.68971,-73.82021,3.0,179.0100,134.0000
2,108151,Radisson Hotel Albany,205 Wolf Rd,Albany,NY,12205,42.72410,-73.79822,3.0,134.1700,84.1600

Choose to use the NY hotel dataset and only keep the Bed & Breakfasts

In [11]:
df2 = pd.read_csv('../data/Bed___Breakfast_Lodging_Certificates.csv')
print(df2.shape)
df2.head(3)

(19, 21)

,PERMIT NUMBER,APPLICATION TYPE,ADDED DATE,ISSUED DATE,FINALED DATE,STREET NUMBER,PRE DIR,STREET NAME,SUFFIX,POST DIR,...,STATE,ZIP CODE,STATUS,FLOORAREA OF HOUSE,FLOORAREA OF GUEST ROOMS,LOT AERA,NUMBER OF GUEST ROOMS,NUMBER OF PARKING SPACE,SPECIAL EXCEPTION,LOCATION
0,200062,BED & BREAKFAST LODGING CERT,09/05/1999,09/05/1999,NaN,8101,NaN,PARK CREST,DR,NaN,...,MD,20910,Issued,0,0,29275,1,1,NaN,"8101 PARK CREST DR\nSILVER SPRING, MD 20910\n(..."
1,200065,BED & BREAKFAST LODGING CERT,09/05/1999,09/05/1999,12/05/2011,2900,NaN,DUBARRY,LN,NaN,...,MD,20833,Finaled,5744,1324,1.7,2,10,NaN,"2900 DUBARRY LN\nBROOKEVILLE, MD 20833\n(39.17..."
2,200064,BED & BREAKFAST LODGING CERT,09/05/1999,09/05/1999,NaN,5422,NaN,MOORLAND,LN,NaN,...,MD,20814,Issued,2598,238,10450,2,3,NaN,"5422 MOORLAND LN\nBETHESDA, MD 20814\n(38.9863..."

In [12]:
# Read Gem / local list 

df_gem = pd.read_excel('../data/local_spots.xlsx')
print(df_gem.shape)
df_gem.head(6)

(6, 11)

,name,address,city,state,zip,type,latitude,longitude,gem,visable,rating
0,Lil' Nony's Bakery,1385 Co Rd 29,", Olmstedville",NY,12857,snack,43.771663,-73.930204,0,1,3
1,It's About Thyme Farm,32 Smith Rd,Olmstedville,NY,12857,shopping,43.779007,-73.951240,1,0,3
2,Natural Stone Bridge & Caves,535 Stone Bridge Rd,Pottersville,NY,12860,Natural wonder,43.747417,-73.851914,0,1,3
3,Natural Stone Bridge & Caves Rock Shop,535 Stone Bridge Rd,Pottersville,NY,12860,Natural wonder,43.747417,-73.851914,0,1,3
4,The Owl at Twilight,1322 Co Rd 29,Olmstedville,NY,12857,resturant,43.771755,-73.924258,0,1,3
5,all bright aquariums,32 Smith Rd,Olmstedville,NY,12857,gift store,43.779534,-73.950862,1,0,7

In [13]:
df_gem.columns

Index(['name ', 'address', 'city', 'state', 'zip', 'type', 'latitude',
       'longitude', 'gem', 'visable ', 'rating'],
      dtype='object')

In [25]:
# write new local_spots as CSV

df_gem.to_csv('../clean_data/local_spots.csv', index = False)

# EDA
<hr/>

In [15]:
# NY Hotel DataSet
#      mask out all non-BnB 

df1 = df[ (df['name'].str.contains('Bed', na =False) == True) ].copy()
df1.reset_index(drop = True, inplace = True)

df1.head(2)

,ean_hotel_id,name,address1,city,state_province,postal_code,latitude,longitude,star_rating,high_rate,low_rate
0,484688,Baldwinsville Bed and Breakfast,70 Oswego Street,Baldwinsville,NY,13027,43.16099,-76.33380,3.5,120.17,119.17
1,486055,Park House Bed and Breakfast,85 Park Street,Binghamton,NY,13905,42.10901,-75.94552,3.0,110.44,95.44

In [16]:
# average as rate

df1['price'] = round ( (df1['high_rate'] + df1['low_rate']) / 2, 2)

In [17]:
# rename columns

df1.rename(columns = {'address1':'address', 'star_rating':'rating','state_province':'state', }, inplace = True )

In [18]:
# drop rows

df1.drop(['ean_hotel_id', 'high_rate','low_rate'], axis = 1, inplace = True)

In [19]:
# add Description

df1['descripton'] = ""

In [23]:
df1.columns

Index(['name', 'address', 'city', 'state', 'postal_code', 'latitude',
       'longitude', 'rating', 'price', 'descripton'],
      dtype='object')

# Output Clean csv
<hr/>

In [27]:
df1

,name,address,city,state,postal_code,latitude,longitude,rating,price,descripton
0,Baldwinsville Bed and Breakfast,70 Oswego Street,Baldwinsville,NY,13027,43.16099,-76.33380,3.5,119.67,
1,Park House Bed and Breakfast,85 Park Street,Binghamton,NY,13905,42.10901,-75.94552,3.0,102.94,
2,Sankofa Aban Bed and Breakfast,107 Macon Street,Brooklyn,NY,11216,40.68136,-73.94700,2.5,192.68,
3,Lefferts Gardens Residence Bed and Breakfast,44 Rutland Road,Brooklyn,NY,11225,40.65887,-73.95907,2.5,144.44,
4,Oyo Bed & Breakfast,1390 Bedford Avenue,Brooklyn,NY,11216,40.67571,-73.95325,2.5,132.52,
5,Hipster's Cove Bed & Breakfast,1300 Sterling Place,Brooklyn,NY,11213,40.67171,-73.93550,2.5,69.66,
6,Illumination Bed & Breakfast,138 Saint James Place,Brooklyn,NY,11238,40.68579,-73.96457,2.5,120.81,
7,Burdett House Bed & Breakfast,3789 Main Street,Burdett,NY,14818,42.41727,-76.85054,3.0,125.71,
8,Bed and Breakfast at Oliver Phelps,252 North Main Street,Canandaigua,NY,14424,42.89552,-77.28726,4.0,189.84,
9,The Bella Ella Bed & Breakfast,2300 Brickyard Rd,Canandaigua,NY,14424,42.91862,-77.32480,3.0,78.20,
10,Filigree Inn Bed & Breakfast,5406 Bristol Valley Road Route 64,Canandaigua,NY,14424,42.75743,-77.40621,3.0,169.55,
11,Blue Horizon Bed and Breakfast,60 Dinch Road,Claryville,NY,12725,41.92017,-74.50429,2.5,150.88,
12,Temple Hill Bed & Breakfast,114 Temple Hill Street,Geneseo,NY,14454,42.79393,-77.80843,3.0,139.85,
13,Harbor Knoll Bed and Breakfast,424 Fourth Street,Greenport,NY,11944,41.09886,-72.36378,4.0,262.58,
14,Ruah Bed & Breakfast,9221 Lake Shore Drive,Hague,NY,12836,43.75100,-73.48694,3.5,160.42,
15,Bellinger Rose Bed & Breakfast,611 W German St,Herkimer,NY,13350,43.02757,-74.99687,2.5,169.01,
16,Stonegate Bed and Breakfast,34 North Road,Highland,NY,12528,41.72659,-73.96506,3.5,150.21,
17,Greenwoods Bed & Breakfast Inn,8136 Quayle Rd,Honeoye,NY,14471,42.80363,-77.48402,3.0,159.10,
18,Journey Inn Bed & Breakfast,1 Sherwood Place,Hyde Park,NY,12538,41.79496,-73.93771,4.0,160.71,
19,JFK Bed & Breakfast Guesthouse,12804 143rd Street,Jamaica,NY,11436,40.67222,-73.79577,2.5,84.16,
20,Spruce Lodge Bed & Breakfast & Guest Cottage,6034 Sentinel Road,Lake Placid,NY,12946,44.27466,-73.98084,2.0,75.41,
21,North Fork Bed and Breakfast/Gifts,219 Baker Road,Lisbon,NY,13658,44.71108,-75.27292,3.0,104.88,
22,The Fox and the Grapes Bed & Breakfast,9496 State Route 414,Lodi,NY,14860,42.56433,-76.86162,3.5,205.81,
23,Mountain Treasure Bed and Breakfast,408 County Route 40,Maplecrest,NY,12454,42.27513,-74.19433,3.0,154.42,
24,Allegiance Bed and Breakfast,145 Main Street,Mount Morris,NY,14510,42.72149,-77.87158,2.5,155.44,
25,Bristol Views Bed and Breakfast,6932 County Rd. 12,Naples,NY,14512,42.68428,-77.37563,3.0,172.54,
26,Harlem Bed and Breakfast,54 West 120th Street,New York,NY,10027,40.80401,-73.94650,1.5,180.00,
27,Allies' Inn Bed and Breakfast,313 West 136th Street,New York,NY,10030,40.81751,-73.94678,3.0,278.00,
28,Beautiful 1 Bedroom Apartment,953 Columbus Avenue,New York,NY,10025,40.79974,-73.96243,3.5,150.81,
29,The Alpine Homestead Bed & Breakfast,1314 County Route 29,Olmstedville,NY,12857,43.77172,-73.92332,3.5,112.67,
30,Finger Lakes Bed and Breakfast,128 South Avenue,Penn Yan,NY,14527,42.65525,-77.05082,3.0,139.86,
31,Cider Mill Inn Bed and Breakfast,207 Glenwood Road,Pine Island,NY,10969,41.27091,-74.47657,3.5,180.40,
32,Windsong Retreat Bed & Breakfast,78 Katrina Falls Road,Rock Hill,NY,12775,41.62259,-74.60281,3.0,159.95,
33,Caldwell House Bed & Breakfast,25 Orrs Mills Road,Salisbury Mills,NY,12577,41.43147,-74.12270,3.0,290.31,
34,Kiwassa Lake Bed & Breakfast and Cabins,1150 Kiwassa Lake Rd,Saranac Lake,NY,12983,44.28782,-74.15834,3.0,275.54,
35,Union Gables Bed & Breakfast,55 Union Ave,Saratoga Springs,NY,12866,43.07720,-73.77986,3.0,225.51,
36,John Morris Manor Bed & Breakfast,2138 Route 89,Seneca Falls,NY,13148,42.92196,-76.75144,3.0,150.47,
37,Fort Place Bed & Breakfast,22 Fort Pl,Staten Island,NY,10301,40.64200,-74.07902,2.0,120.62,
38,The Harbor House Bed & Breakfast,1 Hylan Blvd,Staten Island,NY,10305,40.61548,-74.06338,2.5,129.69,
39,Victorian Bed & Breakfast,92 Taylor Street,Staten Island,NY,10310-1226,40.63676,-74.12343,2.5,140.02,
40,ElmRock Inn Bed and Breakfast,4496 Route 209 Ulster,Stone Ridge,NY,12484,41.82516,-74.18978,4.0,190.18,
41,Rosemont Inn Bed & Breakfast,1423 Genesee Street,Utica,NY,13501,43.09421,-75.24619,3.0,130.26,
42,Tin Brook Bed and Breakfast,2 Berea Road,Walden,NY,12586,41.55842,-74.15907,3.5,147.12,
43,Oakcliff Bed and Breakfast,78 Church Hill Road,Waterford,NY,12188,42.82507,-73.72946,3.5,119.10,

In [22]:
df1.to_csv('../clean_data/bnb_data_list.csv',index = False)